#!/usr/bin/env python 

import argparse
import numpy as np
import nibabel as nib
import matplotlib.pyplot as plt


def bounding_box_3D(img):
    x = np.any(img, axis=(1, 2))
    y = np.any(img, axis=(0, 2))
    z = np.any(img, axis=(0, 1))
    xmin, xmax = np.where(x)[0][[0, -1]]
    ymin, ymax = np.where(y)[0][[0, -1]]
    zmin, zmax = np.where(z)[0][[0, -1]]
    return xmin, xmax, ymin, ymax, zmin, zmax

def crop_img(img, mask):
    xmin, xmax, ymin, ymax, zmin, zmax = bounding_box_3D(img)
    cropped_img = img[xmin:xmax, ymin:ymax, zmin:zmax]
    cropped_mask = mask[xmin:xmax, ymin:ymax, zmin:zmax]
    return cropped_img, cropped_mask


def pick_slices(x, y, total_slices):
    step_sz = total_slices // (x*y)
    slices = list(range(step_sz//2, total_slices+1, step_sz))
    return slices


def slice_img(img, slice_num, slice_axis):
    sliced_img = np.take(img, slice_num, axis=slice_axis)
    oriented_slice = np.flipud(sliced_img.T)
    return oriented_slice


def stack_slices(img, slices, x, y, slice_axis):
    # need to concatenate these in opposite order for FS!
    ind = 0
    for i in range(y):
        for j in range(x):
            slice_num = slices[ind]
            if j == 0:
                row_img = slice_img(img, slice_num, slice_axis)
            else:
                row_img = np.hstack((row_img, slice_img(img, slice_num,
                                                        slice_axis)))
            ind += 1
        if i == 0:
            col_img = row_img
        else:
            col_img = np.vstack((col_img, row_img))
    return col_img


def save_figure(filename, quality):
    if quality == "low":
        output_dpi = 100
    elif quality == "high":
        output_dpi = 300
    else:
        output_dpi = 200
    plt.savefig(filename, dpi=output_dpi, bbox_inches="tight", pad_inches=0)


def parse_input():
    parser = argparse.ArgumentParser()
    parser.add_argument("-b", type=str, required=True, metavar="",
                        help="Base image")
    parser.add_argument("-o", type=str, required=True, metavar="",
                        help="Overlay image")
    parser.add_argument("-s", type=str, required=True, metavar="",
                        help=".png file to save as")
    parser.add_argument("-x", type=int, required=False, default=5, metavar="",
                        help="Number of columns (default: 5)")
    parser.add_argument("-y", type=int, required=False, default=3, metavar="",
                        help="Number of rows (default: 3)")
    parser.add_argument("-q",
                        type=str, required=False, default="medium", metavar="",
                        help="Quality of output figure (low/{medium}/high)")
    args = parser.parse_args()
    return args


def io_stream():
    args = parse_input()
    base = nib.load(args.b)
    overlay = nib.load(args.o)
    if isinstance(base, nib.freesurfer.MGHImage):
        slice_axis = 1
    else:
        slice_axis = 2
    # note that conformed space is 256 isotropic, so special case
    base_cropped, overlay_cropped = crop_img(base.get_data(),
                                             overlay.get_data())
    slices = pick_slices(args.x, args.y, base_cropped.shape[0])
    base_img = stack_slices(base_cropped, slices, args.x, args.y, slice_axis)
    overlay_img = stack_slices(overlay_cropped, slices, args.x, args.y,
                               slice_axis)
    plt.imshow(base_img, cmap="gray")
    if len(np.unique(overlay_cropped)) > 2:
        plt.imshow(overlay_img, cmap="nipy_spectral", alpha=0.35)
    else:
        plt.imshow(overlay_img, cmap="plasma", alpha=0.35)
    plt.axis("off")
    # plt.show()
    if args.s.endswith(".png"):
        save_figure(args.s, args.q)
    else:
        save_figure(args.s + ".png", args.q)


if __name__ == "__main__":
    io_stream()

